name: eis
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh >= 2.0.1
  - ipykernel
  - ipython
  - mpmath >= 1.1.0
  - numpy >= 1.18.4
  - pandas >= 0.22.0
  - pip
  - python >= 3.8
  - scipy >= 1.4.1
  - seaborn
  - jupyter
  - pip:
      - lmfit >= 1.0.1